version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MOCK_MODE=false
      - BLOCKCHAIN_RPC=https://u1q4aby0zt:0HHfp9Fj9YnShcVwSsgaPKz9HkZJbqazpDQfyFOisHk@u1cyktimmj-u1ed8q3cmw-rpc.us1-azure.kaleido.io/
      - CHAIN_ID=23251219
      - CONTRACT_ADDRESS=0x4a223B8a4fcE1aBEa7b15089B1201B7750825d0f
      - CONTRACT_NAME=HitachiNebutaToken
      - CONTRACT_SYMBOL=HNT
      - PRIVATE_KEY=0xdf8326cb6544c65fdcb4682d525ed8b6b8ab068b7435ff784d34e6f54521dca3
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/nft_production
    depends_on:
      - mongodb
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - nft-network

  mongodb:
    image: mongo:7-jammy
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - nft-network

networks:
  nft-network:
    driver: bridge

volumes:
  mongodb_data:
